name: "test Actions"

on:
  workflow_dispatch:
    inputs:
      run1_name:
        required: false
        default: "c$(date '+%y%m%d-%H%M%S')"
        type: string

     
jobs:
  gridai-actions:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo The username is ${{ inputs.run1_name }}
          echo The username2 is ${{ github.event.inputs.run1_name }}
        shell: bash
