name: "test Actions"

on:
  workflow_dispatch:
    inputs:
      run1_name:
        required: false
        default: testfeb16
        type: string

     
jobs:
  gridai-actions:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo The username is ${{ inputs.run1_name }}
        shell: bash
